[package]
name = "bitvector-diff"
version = "0.1.0"
edition = "2024"

[dependencies]
conv = "0.3.3"
fast-math = "0.1.1"
json = "0.12.4"
rand = "0.9.1"
serde = {version = "1.0.219", features = ["derive"]}
serde_json = "1.0.140"
time = "0.3.41"
